In [ ]:
import pandas as pd
income=pd.read_csv("/content/income.csv")
income.head()

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607

In [ ]:
income.columns

Index(['Index', 'State', 'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007',
       'Y2008', 'Y2009', 'Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014', 'Y2015'],
      dtype='object')

In [ ]:
income.loc[:2]

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724

In [ ]:
income.iloc[:,:2]

   Index                 State
0      A               Alabama
1      A                Alaska
2      A               Arizona
3      A              Arkansas
4      C            California
5      C              Colorado
6      C           Connecticut
7      D              Delaware
8      D  District of Columbia
9      F               Florida
10     G               Georgia
11     H                Hawaii
12     I                 Idaho
13     I              Illinois
14     I               Indiana
15     I                  Iowa
16     K                Kansas
17     K              Kentucky
18     L             Louisiana
19     M                 Maine
20     M              Maryland
21     M         Massachusetts
22     M              Michigan
23     M             Minnesota
24     M           Mississippi
25     M              Missouri
26     M               Montana
27     N              Nebraska
28     N                Nevada
29     N         New Hampshire
30     N            New Jersey
31     N            New Mexico
32     N              New York
33     N        North Carolina
34     N          North Dakota
35     O                  Ohio
36     O              Oklahoma
37     O                Oregon
38     P          Pennsylvania
39     R          Rhode Island
40     S        South Carolina
41     S          South Dakota
42     T             Tennessee
43     T                 Texas
44     U                  Utah
45     V               Vermont
46     V              Virginia
47     W            Washington
48     W         West Virginia
49     W             Wisconsin
50     W               Wyoming

In [ ]:
income.dtypes

Index    object
State    object
Y2002     int64
Y2003     int64
Y2004     int64
Y2005     int64
Y2006     int64
Y2007     int64
Y2008     int64
Y2009     int64
Y2010     int64
Y2011     int64
Y2012     int64
Y2013     int64
Y2014     int64
Y2015     int64
dtype: object

In [ ]:
income.Y2008 = income.Y2008.astype(float)
income.dtypes

Index     object
State     object
Y2002      int64
Y2003      int64
Y2004      int64
Y2005      int64
Y2006      int64
Y2007      int64
Y2008    float64
Y2009      int64
Y2010      int64
Y2011      int64
Y2012      int64
Y2013      int64
Y2014      int64
Y2015      int64
dtype: object

In [ ]:
income["index"]

KeyError: 'index'

In [ ]:
income.drop('index',axis = 1)

KeyError: "['index'] not found in axis"

In [ ]:
income.drop([0,1])

In [ ]:
income.sort_values("state",ascending=false)

In [ ]:
import numpy as np
mydata = {'Crop': ['Rice', 'Wheat', 'Barley', 'Maize' ],
'Yield': [1010, 1025.2, 1404.2, 1251.7],
'cost' : [102, np.nan, 20, 68]}
crops - pd. DataFrame (mydata)
crops

NameError: name 'crops' is not defined

In [ ]:
newcrops=crops.dropna

In [1]:
import sqlite3
conn = sqlite3.connect("data.db")
c = conn.cursor()

# DB Functions
def create_usertable():
    c.execute('CREATE TABLE IF NOT EXISTS userstable(Name TEXT,Mobile TEXT,City TEXT, Email TEXT)')
def view_all_users():
    c.execute("SELECT * FROM userstable")
    data = c.fetchall()
    return data

create_usertable()
view_all_users()

SyntaxError: invalid syntax (1652325009.py, line 1)